# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fieldvalue_tags', models.CharField(blank=True, help_text='(Field1:"Value1")(Field2:"Value2")  eg.: (Color:"Rojo")(Carro:{Marca:"Toyota", Modelo:"Rav4", Año:2017})(Opciones:[1, 3, 5])', max_length=1000, verbose_name='Field:Value tags')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('fieldvalue_tags', models.CharField(blank=True, help_text='(Field1:"Value1")(Field2:"Value2")  eg.: (Color:"Rojo")(Carro:{Marca:"Toyota", Modelo:"Rav4", Año:2017})(Opciones:[1, 3, 5])', max_length=1000, verbose_name='Field:Value tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
