# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='fruits',
            field=models.ManyToManyField(to='frutalibre.Fruit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_now',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_original',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
