# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0002_auto_20170401_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fieldvalue_tags', models.CharField(blank=True, help_text='(Field1:"Value1")(Field2:"Value2")  eg.: (Color:"Rojo")(Carro:{Marca:"Toyota", Modelo:"Rav4", Año:2017})(Opciones:[1, 3, 5])', max_length=1000, verbose_name='Field:Value tags')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fieldvalue_tags', models.CharField(blank=True, help_text='(Field1:"Value1")(Field2:"Value2")  eg.: (Color:"Rojo")(Carro:{Marca:"Toyota", Modelo:"Rav4", Año:2017})(Opciones:[1, 3, 5])', max_length=1000, verbose_name='Field:Value tags')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frutalibre.State'),
        ),
    ]
