# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0003_auto_20170401_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location_now',
            new_name='locationNow',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location_original',
            new_name='locationOriginal',
        ),
    ]
