# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0005_auto_20170401_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locationNow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='location_now', to='frutalibre.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='locationOriginal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='location_original', to='frutalibre.Location'),
            preserve_default=False,
        ),
    ]
