# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0006_auto_20170401_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('fieldvalue_tags', models.CharField(blank=True, help_text='(Field1:"Value1")(Field2:"Value2")  eg.: (Color:"Rojo")(Carro:{Marca:"Toyota", Modelo:"Rav4", Año:2017})(Opciones:[1, 3, 5])', max_length=1000, verbose_name='Field:Value tags')),
            ],
        ),
        migrations.CreateModel(
            name='FruitSnap',
            fields=[
                ('mappin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frutalibre.MapPin')),
                ('imageUrl', models.CharField(max_length=300)),
                ('seasonDescription', models.CharField(max_length=300)),
                ('accesibility', models.CharField(choices=[('E', 'Easy'), ('R', 'Regular'), ('C', 'Complicated')], max_length=2)),
                ('quality', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frutalibre.Fruit')),
            ],
            bases=('frutalibre.mappin',),
        ),
    ]
