# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0007_fruitsnap_mappin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitsnap',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fruitsnap',
            name='quality',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')]),
        ),
    ]
