# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0008_auto_20170402_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='idealEnvironment',
            field=models.CharField(default='wepa', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='seasonDescription',
            field=models.CharField(default='yeh', max_length=500),
            preserve_default=False,
        ),
    ]
