# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frutalibre', '0009_auto_20170402_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitsnap',
            name='seasonDescription',
        ),
    ]
